# -*- coding: utf-8 -*-
"""flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11r5egjXU-Ba-untp0rMdBt3u1ACRzebE
"""

!pip install flask-ngrok

import flask
from flask_ngrok import run_with_ngrok
import io
import string
import time
import os
import numpy as np
import joblib
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from flask import Flask, jsonify, request


model_d = tf.keras.models.load_model('model_diabetes.h5')
model_h = tf.keras.models.load_model('model_heart.h5')
model_s = tf.keras.models.load_model('model_stroke.h5')
ss_d = joblib.load('ss_d.bin')
ss_h = joblib.load('ss_h.bin')
ss_s = joblib.load('ss_s.bin')

def prepare_d(datas):
    datas = [datas]
    datas = ss_d.transform(datas)
    return datas
def prepare_h(datas):
    datas = [datas]
    datas = ss_h.transform(datas)
    return datas
def prepare_s(datas):
    datas = [datas]
    datas = ss_s.transform(datas)
    return datas


def predict_diabetes(datas):
    return 1 if model_d.predict(datas)[0][0] > 0.5 else 0
def predict_heart(datas):
    return 1 if model_h.predict(datas)[0][0] > 0.5 else 0
def predict_stroke(datas):
    return 1 if model_s.predict(datas)[0][0] > 0.5 else 0


app = Flask(__name__)
run_with_ngrok(app)

@app.route('/predict', methods=['POST'])
def prediction():
    
    data_d = prepare_d(request.form.getlist('diabetes'))
    data_h = prepare_h(request.form.getlist('heart'))
    data_s = prepare_s(request.form.getlist('stroke'))
    return jsonify({
        "prediction_diabetes":predict_diabetes(data_d),
        "prediction_heart":predict_heart(data_h),
        "prediction_stroke":predict_stroke(data_s)
    })
    

@app.route('/', methods=['GET'])
def index():
    return 'Machine Learning Inference'

app.run()

